export {
  BUILTIN_DEFAULT_IDENTITY_PLUGIN_ID,
  BUILTIN_DIRECT_EGRESS_PLUGIN_ID,
  BUILTIN_HTTP_CONNECT_EGRESS_PLUGIN_ID,
  BUILTIN_LEASED_EGRESS_PLUGIN_ID,
  BUILTIN_LEASED_IDENTITY_PLUGIN_ID,
  BUILTIN_POOL_SERVER_EGRESS_PLUGIN_ID,
  BUILTIN_SOCKS5_EGRESS_PLUGIN_ID,
  BUILTIN_STEALTH_IDENTITY_PLUGIN_ID,
  BUILTIN_TOR_EGRESS_PLUGIN_ID,
  BUILTIN_WIREGUARD_EGRESS_PLUGIN_ID,
} from "./access-allocation-plugin-ids.ts";
export {
  EgressLeaseManagerLive,
  EgressLeaseManagerService,
  EgressPluginRegistry,
  IdentityLeaseManagerLive,
  IdentityLeaseManagerService,
  IdentityPluginRegistry,
  makeEgressPluginRegistryLiveLayer,
  makeIdentityPluginRegistryLiveLayer,
  makeLeaseBackedEgressPlugin,
  makeLeaseBackedIdentityPlugin,
  makeProxyStaticEgressPlugin,
  makeStaticEgressPlugin,
  makeWireGuardEgressPlugin,
  makeStaticEgressPluginRegistry,
  makeStaticIdentityPlugin,
  makeStaticIdentityPluginRegistry,
  resetAccessAllocationPluginStateForTests,
  type EmptyPluginConfig,
  type EgressAllocationPlugin,
  type IdentityAllocationPlugin,
  type LeasedEgressPluginConfig,
  type LeasedIdentityPluginConfig,
  type ProxyEgressPluginConfig,
  type WireGuardEgressPluginConfig,
} from "./access-allocation-plugin-runtime.ts";
export {
  defineAccessRuntimeModule,
  AccessModuleComposition,
  AccessModuleRegistry,
  composeAccessRuntimeModules,
  makeStaticAccessModuleRegistry,
  type AccessRuntimeModule,
  type AccessRuntimeModuleComposition,
} from "./access-module-runtime.ts";
export {
  AccessEngineClosedError,
  createEngine,
  createSdkEngine,
  withEngine,
  type AccessEngine,
  type AccessEngineDecisionTrace,
  type AccessEngineLinkSnapshot,
  type CreateAccessEngineOptions,
} from "./engine.ts";
export {
  normalizeAccessPreviewPayload,
  normalizeAuthoringPayload,
  normalizeExtractRunPayload,
  normalizeRenderPreviewPayload,
  type AccessAuthoringCommandKind,
  type JsonObject,
} from "./authoring.ts";
export {
  AccessCoreRuntimeModuleId,
  HttpConnectAccessRuntimeModule,
  HttpConnectAccessRuntimeModuleId,
  PoolServerAccessRuntimeModule,
  PoolServerAccessRuntimeModuleId,
  Socks5AccessRuntimeModule,
  Socks5AccessRuntimeModuleId,
  TorAccessRuntimeModule,
  TorAccessRuntimeModuleId,
  WireGuardAccessRuntimeModule,
  WireGuardAccessRuntimeModuleId,
  makeAccessCoreRuntimeModule,
  makeAccessModuleRegistryLiveLayer,
  makeBuiltinAccessRuntimeModules,
} from "./access-builtin-modules.ts";
export {
  AccessModuleCompositionLive,
  AccessModuleRegistryLive,
  AccessProfileRegistryLive,
  AccessProviderRegistryLive,
  EgressPluginRegistryLive,
  IdentityPluginRegistryLive,
} from "./access-live-registries.ts";
export {
  AccessSelectionPolicy,
  AccessSelectionPolicyEnvironmentLive,
  AccessSelectionPolicyLive,
  DEFAULT_BROWSER_PROVIDER_ID,
  DEFAULT_HTTP_PROVIDER_ID,
  DEFAULT_STEALTH_BROWSER_PROVIDER_ID,
  makeStaticAccessSelectionPolicy,
  type AccessSelectionDecision,
  type AccessSelectionInput,
} from "./access-policy-runtime.ts";
export {
  AccessSelectionHealthSignalsGateway,
  AccessSelectionHealthSignalsGatewayLive,
  type AccessSelectionHealthInput,
  type AccessSelectionHealthSignals,
} from "./access-selection-health-runtime.ts";
export {
  AccessSelectionStrategy,
  AccessSelectionStrategyLive,
  makeHealthyFirstAccessSelectionStrategy,
  type AccessSelectionCandidate,
  type AccessSelectionStrategyInput,
} from "./access-selection-strategy-runtime.ts";
export {
  AccessExecutionRuntime,
  AccessExecutionRuntimeLive,
  makeBrowserPoolKey,
  materializeExecutionContext,
  toExecutionMetadata,
  type AccessExecutionContext,
  type AccessExecutionInput,
  type ResolvedBrowserExecution,
  type ResolvedExecutionIntent,
  type ResolvedExecutionPlan,
  type ResolvedHttpExecution,
} from "./access-runtime.ts";
export {
  DEFAULT_EGRESS_PROFILE_ID,
  DEFAULT_HTTP_CONNECT_EGRESS_PROFILE_ID,
  DEFAULT_IDENTITY_PROFILE_ID,
  DEFAULT_LEASED_EGRESS_PROFILE_ID,
  DEFAULT_LEASED_IDENTITY_PROFILE_ID,
  DEFAULT_LEASED_STEALTH_IDENTITY_PROFILE_ID,
  DEFAULT_POOL_SERVER_EGRESS_PROFILE_ID,
  DEFAULT_PATCHRIGHT_BROWSER_RUNTIME_PROFILE_ID,
  DEFAULT_PATCHRIGHT_STEALTH_RUNTIME_PROFILE_ID,
  DEFAULT_SOCKS5_EGRESS_PROFILE_ID,
  DEFAULT_STEALTH_IDENTITY_PROFILE_ID,
  DEFAULT_TOR_EGRESS_PROFILE_ID,
  DEFAULT_WIREGUARD_EGRESS_PROFILE_ID,
  AccessProfileRegistry,
  defaultIdentityProfileIdForProvider,
  makeStaticAccessProfileRegistry,
  type AccessEgressProfileDescriptor,
  type AccessIdentityProfileDescriptor,
  type ResolvedEgressProfile,
  type ResolvedIdentityProfile,
} from "./access-profile-runtime.ts";
export {
  type AccessEgressRouteConfig,
  type BrowserLaunchProxyConfig,
  type BunFetchProxyConfig,
  type DirectEgressRouteConfig,
  type ProxyEgressRouteConfig,
  type ProxyEgressRouteKind,
  type WireGuardEgressRouteConfig,
  toBrowserLaunchProxyConfig,
  toBunFetchProxyConfig,
} from "./egress-route-config.ts";
export {
  AccessProfileSelectionHealthSignalsGateway,
  AccessProfileSelectionHealthSignalsGatewayLive,
  type AccessProfileSelectionHealthInput,
  type AccessProfileSelectionHealthSignals,
} from "./access-profile-selection-health-runtime.ts";
export {
  AccessProfileSelectionStrategy,
  AccessProfileSelectionStrategyLive,
  makeDefaultAccessProfileSelectionStrategy,
  type AccessProfileSelectionDecision,
  type AccessProfileSelectionDecisionRationale,
  type AccessEgressProfileSelectionInput,
  type AccessIdentityProfileSelectionInput,
} from "./access-profile-selection-strategy-runtime.ts";
export {
  AccessProfileSelectionPolicy,
  AccessProfileSelectionPolicyEnvironmentLive,
  AccessProfileSelectionPolicyLive,
  makeAccessProfileSelectionPolicy,
  type AccessProfileResolution,
  type AccessProfileResolutionInput,
} from "./access-profile-policy-runtime.ts";
export {
  EgressBroker,
  EgressBrokerEnvironmentLive,
  EgressBrokerLive,
  IdentityBroker,
  IdentityBrokerEnvironmentLive,
  IdentityBrokerLive,
  makeEgressBroker,
  makeIdentityBroker,
  resetAccessBrokerStateForTests,
  type AcquiredEgressSession,
  type AcquiredIdentitySession,
  type EgressBrokerAcquireInput,
  type IdentityBrokerAcquireInput,
  type ResolvedEgressLease,
  type ResolvedIdentityLease,
} from "./access-broker-runtime.ts";
export { AccessExecutionEngine, AccessExecutionEngineLive } from "./access-execution-engine.ts";
export {
  AccessExecutionCoordinator,
  AccessExecutionCoordinatorLive,
  type CoordinatedAccessExecution,
} from "./access-execution-coordinator.ts";
export {
  AccessHealthGateway,
  AccessHealthGatewayLive,
  resetAccessHealthGatewayForTests,
  type AccessHealthContext,
} from "./access-health-gateway.ts";
export {
  AccessHealthPolicyRegistry,
  AccessHealthPolicyRegistryLive,
  AccessHealthSubjectStrategy,
  AccessHealthSubjectStrategyLive,
  makeStaticAccessHealthPolicyRegistry,
  makeStaticAccessHealthSubjectStrategy,
  type AccessHealthSubjectInput,
} from "./access-health-policy-runtime.ts";
export {
  AccessHealthRuntime,
  AccessHealthRuntimeLive,
  type AccessHealthRuntimeService,
} from "./access-health-runtime-service.ts";
export {
  AccessProviderRegistry,
  BuiltinAccessProviderDescriptors,
  makeStaticAccessProviderRegistry,
  type AccessProvider,
  type AccessProviderCapabilities,
  type AccessProviderDescriptor,
  type AccessExecutionResult,
  type AccessExecutionTimings,
} from "./access-provider-runtime.ts";
export {
  BrowserRuntime,
  BrowserRuntimeLive,
  getBrowserPoolSnapshot,
  resetBrowserPoolForTests,
  setBrowserPoolTestConfig,
  withPooledBrowserPage,
  type BrowserPoolLimitsSnapshot,
  type BrowserPoolSnapshot,
  type BrowserRuntimeService,
  type BrowserPoolTestConfig,
  type PatchrightModule,
  type PatchrightPage,
  type PatchrightResponse,
} from "./browser-pool.ts";
export {
  SdkEnvironmentLive,
  SdkRuntimeDependenciesLive,
  SdkRuntimeDerivedLive,
  makeSdkRuntimeHandle,
  SdkRuntimeLive,
  provideSdkEnvironment,
  provideSdkRuntime,
  type SdkEnvironmentServices,
  type SdkRuntimeHandle,
  type SdkRuntimeServices,
} from "./runtime-layer.ts";
export {
  accessPreview,
  extractRun,
  FetchService,
  FetchServiceLive,
  runDoctor,
  renderPreview,
  type FetchClient,
  type FetchRequestInit,
} from "./scraper.ts";
export {
  AccessExecutionMetadataSchema,
  AccessExecutionProfileSchema,
  AccessModeSchema,
  AccessPreviewRequestSchema,
  AccessPreviewResponseSchema,
  AccessProviderIdSchema,
  BrowserExecutionOptionsSchema,
  BrowserWaitUntilSchema,
  EgressRouteKindSchema,
  ExtractRunRequestSchema,
  ExtractRunResponseSchema,
  RenderPreviewArtifactBundleSchema,
  RenderPreviewRequestSchema,
  RenderPreviewResponseSchema,
  type AccessMode,
  type AccessExecutionMetadata,
  type AccessExecutionProfile,
  type AccessProviderId,
  type AccessPreviewRequest,
  type AccessPreviewResponse,
  type BrowserExecutionOptions,
  type BrowserWaitUntil,
  type ExtractRunRequest,
  type ExtractRunResponse,
  type RenderPreviewRequest,
  type RenderPreviewResponse,
} from "./schemas.ts";
export {
  AccessQuarantinedError,
  AccessResourceError,
  BrowserError,
  ExtractionError,
  InvalidInputError,
  NetworkError,
} from "./errors.ts";
